language: haskell

ghc: 
  - 7.8

install:
  - cd hunt-searchengine && cabal install --enable-tests --only-dependencies -ftest-strict
script:
  - cabal configure --enable-tests -ftest-strict && cabal test
